name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.1']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify
      
    - name: Tidy dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./cmd/colog

    - name: Run tests
      run: go test -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build for multiple platforms
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -o colog-linux-amd64 ./cmd/colog
        GOOS=linux GOARCH=arm64 go build -o colog-linux-arm64 ./cmd/colog
        
        # macOS  
        GOOS=darwin GOARCH=amd64 go build -o colog-darwin-amd64 ./cmd/colog
        GOOS=darwin GOARCH=arm64 go build -o colog-darwin-arm64 ./cmd/colog
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -o colog-windows-amd64.exe ./cmd/colog

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: colog-binaries
        path: |
          colog-linux-amd64
          colog-linux-arm64
          colog-darwin-amd64
          colog-darwin-arm64
          colog-windows-amd64.exe